// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwaoTVIhS0iJqwQfJUdNkNOpSOHUlVptE',
    appId: '1:1035086169017:web:f1b4299036f1644205ec68',
    messagingSenderId: '1035086169017',
    projectId: 'fir-demo-e2c7a',
    authDomain: 'fir-demo-e2c7a.firebaseapp.com',
    storageBucket: 'fir-demo-e2c7a.appspot.com',
    measurementId: 'G-D304312NXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOstajg4yt7d7Iuy7KUcYu1DlfiwPnXxs',
    appId: '1:1035086169017:android:4e949e23ffdac18905ec68',
    messagingSenderId: '1035086169017',
    projectId: 'fir-demo-e2c7a',
    storageBucket: 'fir-demo-e2c7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWNBM52bpFlvXW8gj4qPuMyYF2-e0gET0',
    appId: '1:1035086169017:ios:42a57d92f786338105ec68',
    messagingSenderId: '1035086169017',
    projectId: 'fir-demo-e2c7a',
    storageBucket: 'fir-demo-e2c7a.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );
}
